### ISSUE TITLE
Current state of this project?

### ISSUE THREAD

**Issue by fvluijn** [GetDutchie/brick#280]
Hey guys,

First of all: great project! You'd expect the issues solved by this to be more widespread and even natively supported by Flutter.

Anyway, looking at this repository and trying to get it to run (I can't), I'm wondering if this project is abandoned or not?
Do you have plans to maintain it into the foreseeable future? I'd love to help but I'm very new to Flutter and Dart.

I noticed the links on GitHub are old (redirect to your blog), and I can't resolve the deps when following the setup guide:

```
$ flutter pub get
Because brick_offline_first_with_rest_build <1.0.0 depends on brick_offline_first_abstract ^0.0.8 and brick_offline_first_with_rest_build >=1.0.0 depends on brick_offline_first_abstract ^1.0.0+1, every version of brick_offline_first_with_rest_build requires brick_offline_first_abstract ^0.0.8 or ^1.0.0+1.
Because brick_offline_first_with_rest >=1.0.0 depends on brick_offline_first_abstract ^2.0.0 and brick_offline_first_with_rest <1.0.0 depends on brick_offline_first_abstract ^2.0.0-rc.2, every version of brick_offline_first_with_rest requires brick_offline_first_abstract ^2.0.0-rc.2.
Thus, brick_offline_first_with_rest_build is incompatible with brick_offline_first_with_rest.
So, because test depends on both brick_offline_first_with_rest any and brick_offline_first_with_rest_build any, version solving failed.
```
And my pubspec (clean new flutter project via Android Studio).

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  brick_offline_first_with_rest: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  brick_offline_first_with_rest_build: any
  build_runner: any
```

Flutter 3.0.5, Dart 2.17.5

So any hope I can use this in a production environment?

Cheers!

**Comment by tshedor** [comment]
@fvluijn Hey, this is still being actively maintained. Day-to-day has been shifted to the GraphQL domain, but that's not to say the Rest domain is abandoned. I'll see what I can diagnose about this error tomorrow.

**Comment by fvluijn** [comment]
@tshedor that's good to hear. Haven't looked as closely at the GraphQL part, might be interesting to use as well. I'll try and see if those packages do resolve.

**Comment by fvluijn** [comment]
Alright, just to confirm the packages do resolve when using the GraphQL packages:

```
dependencies:
  brick_offline_first_with_graphql: any
dev_dependencies:
  brick_offline_first_with_graphql_build: any
  build_runner: any
```
