### ISSUE TITLE
Is @ConnectOfflineFirstWithRest() part of Brick 2 or Brick 1?

### ISSUE THREAD

**Issue by CyMathew** [GetDutchie/brick#281]
Trying out brick in a test Flutter app but I'm not sure if I'm following the latest documentation.
According to #263, `brick_offline_first` is now, fundamentally, `brick_offline_first_with_rest`.

While creating a model according to https://getdutchie.github.io/brick/#/data/models , I saw the use of `@ConnectOfflineFirstWithRest()`. Is `@ConnectOfflineFirstWithRest()` part of Brick 2 or Brick 1?
```dart
@ConnectOfflineFirstWithRest()
class User extends OfflineFirstModel {}
```

Currently my pubspec.yaml looks like this:

```yaml

dependencies:
    flutter:
       sdk: flutter
...
    brick_offline_first: ^2.1.1
    brick_offline_first_abstract: ^2.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.1.11
    brick_offline_first_build: ^2.0.0+1
```

Does the pubspec.yaml look correct? If so, which package do I need to add to get `@ConnectOfflineFirstWithRest()` annotation?
I may be overcomplicating this.

**Comment by tshedor** [comment]
@CyMathew Thanks for opening this issue and using Brick. 

In v1, `brick_offline_first` contained all rest-specific logic. That logic was moved to its own package, `brick_offline_first_with_rest`. `brick_offline_first` contains provider-agnostic code, so it's still relevant, but it should be rarely used directly. 

`ConnectOfflineFirstWithRest` is used in both v1 and v2. It's necessary to build the correct generated adapters. 

In v1, it would be imported like you have in your `pubspec.yaml`. 

However, in v2, it would be imported via the [domain-specific](https://github.com/GetDutchie/brick/blob/main/example/pubspec.yaml#L13-L22) packages because `brick_offline_first_with_rest` is now a superset of `brick_offline_first`: 

```yaml
dependencies:
  brick_offline_first_with_rest: any

dev_dependencies:
  brick_offline_first_with_rest_build: any
  build_runner: any
```

Does that make sense?
