### ISSUE TITLE
Dependencies Issue

### ISSUE THREAD

**Issue by SubutaDan** [GetDutchie/brick#386]
Are the instructions here:

https://getdutchie.github.io/brick/#/?id=quick-start

still valid?

I created an auto-generated Counter project and made the specified changes to 
pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  dependencies:
  # Or brick_offline_first_with_graphql
  brick_offline_first_with_rest: 
  sqflite: # optional

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  brick_offline_first_with_rest_build:
```
When 'pub get' ran the result was:

```
The current Dart SDK version is 3.4.0.

Because brick_deps depends on dependencies any which doesn't support null safety, version solving failed.

The lower bound of "sdk: '>=2.0.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety
exit code 1
```
Thanks very much.
